[package]
name = "maturin"
version = "0.1.0"
authors = ["scpointer <956096260@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy_system_allocator = "0.5"
bitflags = "1.2.1"
xmas-elf = "0.7"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
lock = { git = "https://gitee.com/chyyuu/kernel-sync.git"}
riscv = { git = "https://gitee.com/chyyuu/riscv.git", features = ["inline-asm"] }
bitmap-allocator = { path = "../bitmap-allocator" }
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers" }
easy-fs = { path = "../easy-fs" }
fatfs = { path = "../rust-fatfs", version = "0.4", default-features = false, features = ["alloc", "lfn"] }
fscommon = { path = "../fscommon", version = "0.1.1" }

