[package]
name = "maturin"
version = "0.1.0"
authors = ["scpointer <956096260@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy_system_allocator = "0.5"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
lock = { git = "https://github.com/DeathWish5/kernel-sync.git"}
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
trapframe = "0.9"